### ISSUE TITLE
UnboundLocalError: local variable 'pw' referenced before assignment

### ISSUE THREAD

**Issue by sanskubu** [ohhdemgirls/CaptureBate#13]
Hi, I was getting this error(see below), but was able to fix it by add "" around pw on line 103 in modellists.py. Not sure if this is correct way of fixing it but it worked for me. Now if I could just figure out how to fix the 0 byte file issue.

Traceback (most recent call last):
  File "main.py", line 25, in <module>
    modellists.Get_links(client, Selected_models)
  File "/media/.../modellists.py", line 103, in Get_links
    "pw_hash": pw,
UnboundLocalError: local variable 'pw' referenced before assignment

**Comment by sanskubu** [comment]
It appears that my fix, fixed the error but not the issue. From the logs looks like the program is running as if I am not logged in to the website. Might be why I'm seeing 0 byte files?

**Comment by sanskubu** [comment]
Issue was on my end. Sorry for the non-issue.
