### ISSUE TITLE
when i run the main.js that is happen , and other change?

### ISSUE THREAD

**Issue by p1020119** [ohhdemgirls/CaptureBate#28]
/home/xx/c/node_modules/js-yaml/lib/js-yaml/loader.js:168
  throw generateError(state, message);
  ^
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 8, column 1:
    
    ^
    at generateError (/home/xx/c/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/home/xx/c/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockMapping (/home/xx/c/node_modules/js-yaml/lib/js-yaml/loader.js:1041:9)
    at composeNode (/home/xx/c/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readDocument (/home/xx/c/node_modules/js-yaml/lib/js-yaml/loader.js:1489:3)
    at loadDocuments (/home/xx/c/node_modules/js-yaml/lib/js-yaml/loader.js:1545:5)
    at load (/home/xx/c/node_modules/js-yaml/lib/js-yaml/loader.js:1562:19)
    at Object.safeLoad (/home/xx/c/node_modules/js-yaml/lib/js-yaml/loader.js:1580:10)
    at Object.<anonymous> (/home/xx/c/main.js:278:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by yug95** [comment]
i also got same issue check indentation if you are using swagger or any comment
