### ISSUE TITLE
UnboundLocalError local variable 'pw' referenced before assignment

### ISSUE THREAD

**Issue by msr65** [ohhdemgirls/CaptureBate#29]
Getting this error starting main.py.

File "main.py", line 25, in ,module>
modellists.Get_links(client, Selected_models)
File "root/CaptureBate/modellists.py", line 103, in Get_links
"pw_hash":pw,
UnboundLocalError local variable 'pw' referenced before assignment

**Comment by kingkk789** [comment]
i am also getting same error 
File "main.py", line 25, in <module>
    modellists.Get_links(client, Selected_models)
  File "/root/CaptureBate/modellists.py", line 103, in Get_links
    "pw_hash": pw,
UnboundLocalError: local variable 'pw' referenced before assignment

**Comment by interbiznw** [comment]
Same here, Anyone figure it out?

**Comment by interbiznw** [comment]
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    modellists.Get_links(client, Selected_models)
  File "/home/chaturbatecaps/CaptureBate-master/modellists.py", line 103, in Get_links
    "pw_hash": pw,
UnboundLocalError: local variable 'pw' referenced before assignment

**Comment by kaminari8888** [comment]
same

**Comment by yodahome** [comment]
Same here, only started today.

**Comment by interbiznw** [comment]
Today? Odd mine started on the 6th around noon pst. After looking into it..looks like a site change has caused the issue

**Comment by Mutini** [comment]
See if this fixes the problem.

open modellists.py

find:
`pw_match = re.search(r"password:\s'(pbkdf2_sha256.*[\\u003D|=])", line)`

change to:
`pw_match = re.search(r"password:\s'(.*?.{120,})'", line)`

**Comment by kingkk789** [comment]
See if this fixes the problem.

open modellists.py

find:
pw_match = re.search(r"password:\s'(pbkdf2_sha256.*[\\u003D|=])", line)

change to:
pw_match = re.search(r"password:\s'(.*?.{120,})'", line)

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    import modellists
  File "/root/test/CaptureBate/modellists.py", line 82
    pw_match = re.search(r"password:\s'(.*?.{120,})'", line)
    ^
IndentationError: unexpected indent

**Comment by msr65** [comment]
FIxed by @Mutini   Thanks!

-----------------------------------------------------------------------------------
See if this fixes the problem.

open modellists.py

find:
pw_match = re.search(r"password:\s'(pbkdf2_sha256.*[\\u003D|=])", line)

change to:
pw_match = re.search(r"password:\s'(.*?.{120,})'", line)

**Comment by Mutini** [comment]
@kingkk789 the Python programming language uses indents to differentiate blocks of code. You pasted the line without the proper indent, hence the error.

If you don't remember how the line was exactly indented, then copy the  modellists.py code from the repository, replace your copy entirely, then try again, this time to ensure you paste the line EXACTLY how it was originally indented.

**Comment by msr65** [comment]
Thanks Mutini! 

Someone needs to pull the modellists.py file and update line 82.

**Comment by Mutini** [comment]
@msr65 we should leave this thread open until a proper commit fixing this issue is added to the repo. Otherwise there's gonna be new threads cropping up.

**Comment by msr65** [comment]
Done!

**Comment by kingkk789** [comment]
msr65 now its works but recording clip size 0 kb

**Comment by msr65** [comment]
@kingkk789 I think that is a separate issue.

**Comment by kingkk789** [comment]
@msr65  can i get u r email address or facebook id i need to talk with

**Comment by kingkk789** [comment]
After 
change to:
pw_match = re.search(r"password:\s'(.*?.{120,})'", line)
that script not recording any thing say solution guys :) thanks in advance

**Comment by interbiznw** [comment]
> See if this fixes the problem.

open modellists.py

find:
pw_match = re.search(r"password:\s'(pbkdf2_sha256.*[\\u003D|=])", line)

change to:
pw_match = re.search(r"password:\s'(.*?.{120,})'", line)

Worked like a charm! thanks!

**Comment by kingkk789** [comment]
@interbiznw u r script recording shows ???

**Comment by dhearns** [comment]
@kingkk789 did your script ever record prior to the recent site change? Sounds like it didn't.  I've had problems with 0 byte files in the past and the root cause was the wrong RTMPDUMP path in config.conf.  Have you installed rtmpdump & does yours look like this? RTMPDUMP = /usr/local/bin/rtmpdump

**Comment by interbiznw** [comment]
Yes

**Comment by kingkk789** [comment]
@dhearns  can u sent me u r updated config.conf file

**Comment by interbiznw** [comment]
Who?

**Comment by kingkk789** [comment]
@ interbiznw  if u r scripts works sent u r script on papu.acer@gmail.com

**Comment by kingkk789** [comment]
[url]
URL = https://chaturbate.com/auth/login/
URL_FOLLOWED = https://chaturbate.com/followed-cams/
URL_SPY_SHOWS = https://chaturbate.com/spy-on-cams/
[folders]
OUTPUT_FOLDER = /mnt/capturebate/
VIDEO_FOLDER = /home/vps/public_html/CaptureBate/Captured
SCRIPTS_FOLDER = /home/vps/public_html/CaptureBate/scripts
DEBUG_FOLDER = debugs
[files]
LOG_FILE =
WANTED_FILE = wanted.txt
[delays]
DELAY = 45
[version]
VERSION = 7.4
[debug]
DEBUGGING = False
[advanced]
RTMPDUMP = /usr/local/bin/rtmpdump
MINIMAL_RECORDING_SIZE_IN_MB = 10

when i run python main.py
root@server:/home/vps/public_html/CaptureBate# python main.py
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    Preconditions(SCRIPTS_FOLDER)
  File "/home/vps/public_html/CaptureBate/config.py", line 62, in Preconditions
    os.mkdir(folder)
OSError: [Errno 20] Not a directory: '/mnt/capturebate//home/vps/public_html/CaptureBate/scripts'


how to fix it guys

**Comment by interbiznw** [comment]
That's a path error, saying your directory does not exist.

notice the double slash " // " 

> /mnt/capturebate//home/vps/public_html/CaptureBate/scripts
