### ISSUE TITLE
Preconditions os.mkdir(folder)

### ISSUE THREAD

**Issue by kingkk789** [ohhdemgirls/CaptureBate#33]
[url]
URL = https://chaturbate.com/auth/login/
URL_FOLLOWED = https://chaturbate.com/followed-cams/
URL_SPY_SHOWS = https://chaturbate.com/spy-on-cams/
[folders]
OUTPUT_FOLDER = /mnt/capturebate/
VIDEO_FOLDER = /home/vps/public_html/CaptureBate/Captured
SCRIPTS_FOLDER = /home/vps/public_html/CaptureBate/scripts
DEBUG_FOLDER = /home/vps/public_html/CaptureBate/debugs
[files]
LOG_FILE = output.log.txt
WANTED_FILE = wanted.txt
[delays]
DELAY = 45
[version]
VERSION = 7.4
[debug]
DEBUGGING = False
[advanced]
RTMPDUMP = /usr/local/bin/rtmpdump
MINIMAL_RECORDING_SIZE_IN_MB = 10

when i run python main.py
root@server:/home/vps/public_html/CaptureBate# python main.py
Traceback (most recent call last):
File "main.py", line 15, in
Preconditions(SCRIPTS_FOLDER)
File "/home/vps/public_html/CaptureBate/config.py", line 62, in Preconditions
os.mkdir(folder)
OSError: [Errno 2] No such file or directory: '/mnt/capturebate//home/vps/public_html/CaptureBate/scripts'

how to fix it guys

**Comment by dhearns** [comment]
@kingkk789 see @interbiznw comment from issue #29. Try changing the "//" to "/" and give it another shot.

> That's a path error, saying your directory does not exist.

> notice the double slash " // "

> /mnt/capturebate//home/vps/public_html/CaptureBate/scripts

**Comment by kingkk789** [comment]
hey guys can u sent me u r working script to my mail id :-papu.acer@gmail.com

**Comment by dhearns** [comment]
@kingkk789 you're using a different version of config.conf than I am so my scripts most likely won't be compatible with your setup.

**Comment by kingkk789** [comment]
sent me once i try if it works for me :)

**Comment by kingkk789** [comment]
which version script u r using :- https://github.com/superagentp/CaptureBate
https://github.com/ohhdemgirls/CaptureBate
https://github.com/redyready1/CaptureBate

**Comment by interbiznw** [comment]
https://github.com/ohhdemgirls/CaptureBate/blob/master/config.conf

**Comment by dhearns** [comment]
@kingkk789 ohhdemgirls version

**Comment by interbiznw** [comment]
@kingkk789 where did you get that version of the config file?

**Comment by interbiznw** [comment]
@kingkk789 was it from another fork? Looks like theres more features. i.e. the spy on cams thing and the minimal recording size.

**Comment by kingkk789** [comment]
in https://github.com/ohhdemgirls/CaptureBate scripts file record size  0 byte how i fix this

**Comment by dhearns** [comment]
Have you addressed the double slash "//" yet?

**Comment by interbiznw** [comment]
You have multiple issues going on please stick to one until it is resolved

**Comment by kingkk789** [comment]
[url]
URL = https://chaturbate.com/auth/login/
URL_follwed = https://chaturbate.com/followed-cams/
[credentials]
USER = kxxxxx
PASS = Sxxxx
[folders]
Video_folder = /home/vps/public_html/video
Script_folder = /root/CaptureBate/Scripts
[files]
Log_file = output.log
wishlist_file = wishlist.txt
[delays]
Time_delay = 45
[version]
Version = 7.0
[debug]
Debugging = False
[advanced]
RTMPDUMP = /usr/bin/rtmpdump

i m using this script and error is  0 byte how i fix it

**Comment by interbiznw** [comment]
0 Bytes is most likely due to wrong version of rtmpdump

**Comment by kingkk789** [comment]
how to fix it interbiznw and how add path of rtmpdump

**Comment by kingkk789** [comment]
ok bro i am uninstall rtmpdump now how to install rtmpdump . with command git clone https://github.com/BurntSushi/rtmpdump-ksv.git ?
then how i set the path ?

**Comment by chetancc** [comment]
Hi Guys,

Can you help me to install this setup or send me step by step document? I
am new to this.

Chetan

**Comment by kingkk789** [comment]
is this the command ?
git clone https://github.com/BurntSushi/rtmpdump-ksv
cd rtmpdump-ksv
make
make install
cp librtmp/librtmp.so.1 /usr/lib

**Comment by kingkk789** [comment]
now error is ./couplehornyy69.sh: 2: ./couplehornyy69.sh: /usr/bin/rtmpdump: not found

**Comment by interbiznw** [comment]
Can you type just  "rtmpdump" in shell and does it run rtmpdump?

**Comment by kingkk789** [comment]
root@debian-512mb-sgp1-02:~# rtmpdump
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
ERROR: You must specify a hostname (--host) or url (-r "rtmp://host[:port]/playpath") containing a hostname

**Comment by interbiznw** [comment]
Type " whereis rtmpdump " in shell, past output

**Comment by kingkk789** [comment]
root@debian-512mb-sgp1-02:~# whereis rtmpdump
rtmpdump: /usr/local/bin/rtmpdump

**Comment by interbiznw** [comment]
so you have 2 options. For rtmpdump path you can just put

" rtmpdump " or the full path " /usr/local/bin/rtmpdump "

Both should work

**Comment by kingkk789** [comment]
[url]
URL = https://chaturbate.com/auth/login/
URL_follwed = https://chaturbate.com/followed-cams/
[credentials]
USER = xxxx
PASS = xxx
[folders]
Video_folder = /home/vps/public_html/video
Script_folder = /root/CaptureBate/Scripts
[files]
Log_file = output.log
wishlist_file = wishlist.txt
[delays]
Time_delay = 45
[version]
Version = 7.0
[debug]
Debugging = False
[advanced]
RTMPDUMP = /usr/local/bin/rtmpdump

**Comment by interbiznw** [comment]
My config just has " RTMPDUMP = rtmpdump " because it is runnable by just typing the command alone.

**Comment by kingkk789** [comment]
same problem bro  0 Bytes

**Comment by interbiznw** [comment]
Your gonna have to enable debugging and see where the error comes in

**Comment by interbiznw** [comment]
Did you compile RTMPDUMP like instructed on the readme on that repo?

**Comment by interbiznw** [comment]
i believe you need to do the ssl stuff that is listed also

**Comment by kingkk789** [comment]
bro can u sent me u r working sript in my mail id :-papu.acer@gmail.com

**Comment by interbiznw** [comment]
My working script is not going to do anything for your system that is misconfigured. I am using the script straight off this repo.

**Comment by interbiznw** [comment]
You need to follow every step of the setup for rtmpdump

**Comment by kingkk789** [comment]
say me how to install rtmpdump

**Comment by interbiznw** [comment]
https://github.com/BurntSushi/rtmpdump-ksv/blob/ksv/README

**Comment by interbiznw** [comment]
"This code also requires you to have OpenSSL and zlib installed"

**Comment by kingkk789** [comment]
ok wait bro i m installing

**Comment by dhearns** [comment]
Try this, step-by-step:
1. `git clone https://github.com/BurntSushi/rtmpdump-ksv.git` 
2. `cd rtmpdump-ksv`
3. `make SYS=posix`
4. `make XDEF=-DNO_SSL`
5. `make install`

**Comment by kingkk789** [comment]
root@debian-512mb-sgp1-02:~# cd rtmpdump-ksv
root@debian-512mb-sgp1-02:~/rtmpdump-ksv# make SYS=posix
make[1]: Entering directory `/root/rtmpdump-ksv/librtmp'
gcc -Wall   -DRTMPDUMP_VERSION=\"v2.4\" -DUSE_OPENSSL  -O2 -fPIC   -c -o rtmp.o rtmp.c
rtmp.c:61:25: fatal error: openssl/ssl.h: No such file or directory
compilation terminated.
make[1]: *** [rtmp.o] Error 1
make[1]: Leaving directory `/root/rtmpdump-ksv/librtmp'
make: *** [librtmp/librtmp.a] Error 2
root@debian-512mb-sgp1-02:~/rtmpdump-ksv# make XDEF=-DNO_SSL
make[1]: Entering directory `/root/rtmpdump-ksv/librtmp'
gcc -Wall   -DRTMPDUMP_VERSION=\"v2.4\" -DUSE_OPENSSL -DNO_SSL -O2 -fPIC   -c -o rtmp.o rtmp.c
rtmp.c:61:25: fatal error: openssl/ssl.h: No such file or directory
compilation terminated.
make[1]: *** [rtmp.o] Error 1
make[1]: Leaving directory `/root/rtmpdump-ksv/librtmp'
make: *** [librtmp/librtmp.a] Error 2
root@debian-512mb-sgp1-02:~/rtmpdump-ksv# make install
make[1]: Entering directory `/root/rtmpdump-ksv/librtmp'
gcc -Wall   -DRTMPDUMP_VERSION=\"v2.4\" -DUSE_OPENSSL  -O2 -fPIC   -c -o rtmp.o rtmp.c
rtmp.c:61:25: fatal error: openssl/ssl.h: No such file or directory
compilation terminated.
make[1]: *** [rtmp.o] Error 1
make[1]: Leaving directory `/root/rtmpdump-ksv/librtmp'
make: *** [librtmp/librtmp.a] Error 2

**Comment by interbiznw** [comment]
Theres your problem: " fatal error: openssl/ssl.h: No such file or directory compilation terminated "

**Comment by dhearns** [comment]
run `whereis openssl` or `which openssl`.  What does it say?

**Comment by kingkk789** [comment]
root@debian-512mb-sgp1-02:~# whereis openssl
openssl: /usr/bin/openssl /usr/bin/X11/openssl /usr/share/man/man1/openssl.1ssl.gz
root@debian-512mb-sgp1-02:~# which openssl
/usr/bin/openssl
root@debian-512mb-sgp1-02:~#

**Comment by dhearns** [comment]
i don't see /usr/include/openssl in your wereis openssl results.  That's where ssl.h is located in my filesystem.  Try reinstalling openssl?

**Comment by kingkk789** [comment]
okk i m trying

**Comment by interbiznw** [comment]
Figure it out?
